Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Metrics/AbcSize:
  Enabled: false

Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 120


AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - 'vendor/**/*'
    - 'bin/*'
    - 'Gemfile.lock'
    - 'Rakefile'
